name: Test

on:
  push:
    branches:
      - "**"

  pull_request:

jobs:
  test-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.20.1

      - uses: actions/checkout@v3

      - run: go run github.com/ysmood/golangci-lint@latest

      - run: go test ./...
